server:
  port: 8080

spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      routes: #路由模型，内包含断言模型和过滤器模型
        - id: route-consumer
          uri: lb://service-consumer #uri的schema协议为自定义的lb:类型，表示从微服务注册中心（如Eureka）订阅服务，并且进行服务的路由
          predicates: #断言模型
            - Path=/consumer/**
          filters: #过滤器模型
            - StripPrefix=1
        - id: route-provider
          uri: lb://service-provider
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
      locator:
        enabled: false
        lower-case-service-id: on #开启小写验证，默认feign根据服务名查找用的都是大写

#暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: on
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
