server:
  port: 8050

spring:
  application:
    name: turbine-server

eureka:
  client:
    service-url:
      defaultZone: http://song:song12345@172.17.0.2:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

turbine:
  app-config: consumer-movie,consumer-movie2 #指定了需要收集监控信息的服务名；
  cluster-name-expression: new String("default") #指定集群名称为default，当我们服务数量非常多的时候，可以启动多个Turbine服务来构建不同的聚合集群，而该参数可以用来区分这些不同的聚合集群，同时该参数值可以在Hystrix仪表盘中用来定位不同的聚合集群，只需要在Hystrix Stream的URL中通过cluster参数来指定；
#  instanceUrlSuffix: hystrix.stream
