server:
  port: 8082

spring:
  application:
    name: service-consumer

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5 #定义服务续约任务的调用间隔时间，默认30s
    lease-expiration-duration-in-seconds: 10 #定义eureka server自接受上次心跳服务失效的时间，默认90s
    prefer-ip-address: true #设置主机名使用IP地址
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

