server:
  port: 8082

spring:
  application:
    name: service-consumer

eureka:
  instance:
    prefer-ip-address: on
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

