server:
  port: 6101

#设置eurekaServer的登录密码
spring:
  security:
    user:
      name: song  # 用户名
      password: song12345 # 用户密码

eureka:
  instance:
    hostname: peer1 #默认是操作系统主机名，若在同一个ip下搭建高可用模式环境时，建议自定义主机名，以区分各节点
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} #自定义instanceid命名规则
#    prefer-ip-address: true # 如果在同一个ip下搭建高可用模式环境时，建议为false
  client:
    register-with-eureka: false # 是否向注册中心注册自己，默认是true,eureka单节点模式设置为false，eureka高可用模式设置为true
    fetch-registry: false #是否向注册中心检索服务，默认是true，设置同eureka.client.register-with-eureka
    service-url:
      defaultZone: http://song:song12345@peer1:6101/eureka/ #已增加eureka server服务注册中心加入安全校验
  server:
    enable-self-preservation: false #eureka server是否开启自我保护机制，默认是true，本地调式时建议关闭
#    peer-node-read-timeout-ms: 500 #高可用模式下，设置eureka server伙伴节点读取超时时间，单位毫秒

