server:
  port: 8762

spring:
  security:
    user:
      name: xian
      password: xian12345

eureka:
  instance:
    hostname: peer2
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://song:song12345@peer1:8761/eureka/,http://zhuo:zhuo12345@peer3:8763/eureka/
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 500
    eviction-interval-timer-in-ms: 4000